version: '3'

# Anchor functions
x-volumefunc: &xvolumefunc
  volumes:
    - ./templates:/app/templates:cached

services:
  pythonapp:
    container_name: pipedrive
    labels:
      NAME: "pipedrive"
    restart: always
    build: ./
    environment:
      PIPEDRIVE_API_TOKEN: "change_api_token_here"
    <<: *xvolumefunc
    ports:
      - 8080:8080
  cronjob:
    container_name: cronjob
    labels:
      NAME: "cronjob"
    build:
      context: .
      dockerfile: cronjob/Dockerfile
    <<: *xvolumefunc
